name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel
            ~/.cache/bazelisk
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', 'MODULE.bazel', 'MODULE.bazel.lock') }}
          restore-keys: |
            ${{ runner.os }}-bazel-
            
      - name: Setup bazelisk
        uses: bazelbuild/setup-bazelisk@v3
        
      - name: Build all targets
        run: |
          bazel build //...
          
      - name: Run all tests
        run: |
          bazel test //...
          
      - name: Build test workspace
        run: |
          cd testdata/basic_lake
          bazel build //...
